"""
SupportPilot AI

QA Report Generator

Generates and prints Quality Assurance reports
for automated module testing.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

logger = logging.getLogger(__name__)


class QAReport:
    """
    Generates QA summary reports for automated tests.
    """

    # ---------------------------------------------------
    # Generate Report
    # ---------------------------------------------------

    @staticmethod
    def generate(
        results: dict[str, dict[str, Any]],
    ) -> dict[str, Any]:
        """
        Generate a QA report.

        Parameters
        ----------
        results : dict
            Dictionary containing module test results.

        Returns
        -------
        dict
            QA summary report.
        """

        logger.info("Generating QA report.")

        passed = 0
        failed = 0

        for result in results.values():

            if result.get("status") == "PASS":
                passed += 1
            else:
                failed += 1

        report = {
            "generated_at": datetime.now().strftime(
                "%Y-%m-%d %H:%M:%S"
            ),
            "total_tests": len(results),
            "passed": passed,
            "failed": failed,
            "details": results,
        }

        logger.info(
            "QA report generated successfully "
            "(Passed=%s, Failed=%s).",
            passed,
            failed,
        )

        return report

    # ---------------------------------------------------
    # Print Report
    # ---------------------------------------------------

    @staticmethod
    def print_report(
        report: dict[str, Any],
    ) -> None:
        """
        Print a formatted QA report.

        Parameters
        ----------
        report : dict
            Report generated by generate().
        """

        print("\n" + "=" * 60)
        print("SUPPORTPILOT QA REPORT")
        print("=" * 60)

        print(
            f"Generated At : "
            f"{report.get('generated_at')}"
        )

        print(
            f"Total Tests  : "
            f"{report.get('total_tests')}"
        )

        print(
            f"Passed       : "
            f"{report.get('passed')}"
        )

        print(
            f"Failed       : "
            f"{report.get('failed')}"
        )

        print("\nTest Results")
        print("-" * 60)

        details = report.get(
            "details",
            {},
        )

        if not details:

            print("No test results available.")

        else:

            for module, result in details.items():

                status = result.get(
                    "status",
                    "UNKNOWN",
                )

                message = result.get(
                    "message",
                    "",
                )

                print(
                    f"{module:<30}"
                    f"{status:<10}"
                    f"{message}"
                )

        print("=" * 60 + "\n")


# ---------------------------------------------------
# Public Exports
# ---------------------------------------------------

__all__ = [
    "QAReport",
]